version: 2
updates:
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
    labels: &ref_0
      - dependencies
  - package-ecosystem: cargo
    directory: /tools/fetch-reports
    schedule:
      interval: weekly
    labels: *ref_0
