name: CI

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.ref }}
  cancel-in-progress: ${{ github.event_name == 'pull_request' }}

on:
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: [self-hosted, linux, x64, light]
    steps:
      - uses: actions/checkout@v6

      - name: Install Zola
        uses: taiki-e/install-action@v2
        with:
          tool: zola@0.22.1

      - name: Build
        run: zola build
